import { Project } from './supabase'

export const DEMO_PROJECTS: Project[] = [
  {
    id: '1',
    slug: 'character-rig-pipeline',
    title: 'Character Rig Pipeline',
    category: 'Pipeline',
    tags: ['Python', 'Maya', 'Automation'],
    description: 'Automated rigging pipeline for production characters at EA Motive, cutting setup time by 60%.',
    writeup: `## Overview\n\nBuilt a Python-based rigging pipeline in Maya that automated repetitive setup tasks for the Dead Space remake production at EA Motive Studio.\n\n## Technical Approach\n\nThe pipeline used Maya's Python API to parse incoming geometry, auto-detect joint hierarchies, and apply studio-standard deformer stacks. A custom UI panel let animators override defaults without touching code.\n\n## Results\n\n- 60% reduction in per-character rig setup time\n- Standardized deformer stack across 40+ characters\n- Zero manual intervention for LOD binding`,
    cover_url: '',
    media: [],
    featured: true,
    order_index: 0,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'niagara-vfx',
    title: 'Niagara VFX System',
    category: 'VFX',
    tags: ['UE5', 'Niagara', 'HLSL'],
    description: 'Real-time particle effects system for environmental storytelling in Unreal Engine 5.',
    writeup: `## Overview\n\nDesigned a modular Niagara particle system for environmental VFX, built for reuse across multiple level types.\n\n## Technical Approach\n\nCustom HLSL noise functions drove organic motion without expensive simulation. Blueprint-exposed parameters let level designers art-direct each instance without touching the Niagara graph.\n\n## Highlights\n\n- GPU particle simulation, 10k+ particles at 60fps\n- Fully data-driven: color, scale, density exposed to Blueprint\n- Custom ribbon renderer for volumetric light shafts`,
    cover_url: '',
    media: [],
    featured: true,
    order_index: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'toon-shader',
    title: 'Toon Shader — UE5',
    category: 'Technical Art',
    tags: ['HLSL', 'UE5', 'Shaders'],
    description: 'Hand-crafted toon shader with dynamic rim lighting and ink-line post-process pass.',
    writeup: `## Overview\n\nA stylized toon shader built in UE5's material editor, extended with custom HLSL nodes for ink-line rendering.\n\n## Technical Approach\n\nUsed scene depth and normal discontinuities to drive a post-process edge detection pass. The cel-shading ramp is texture-driven so artists can change the look without recompiling the shader.\n\n## Features\n\n- Texture-driven shading ramp\n- Depth-based edge detection\n- Specular matcap layer for glossy accents`,
    cover_url: '',
    media: [],
    featured: false,
    order_index: 2,
    created_at: new Date().toISOString(),
  },
]
